### ISSUE TITLE
v5 incompatibility with gnome-shell version lower than 3.32

### ISSUE THREAD

**Issue by JayBeeDe** [oae/gnome-shell-minimize-to-tray#11]
Thank you for the new version, I will test it at home with my Ubuntu 20.
Regarding my enterprise laptop, I'm still stuck with a Ubuntu 18 (gnome-shell version 3.28).
When I try to open the settings (with my enterprise laptop) from the gnome tweaks Extensions section, I get:
```
TypeError: imports.misc.extensionUtils.getSettings is not a function

Stack trace:
  exports.getCurrentExtensionSettings@/home/user/.local/share/gnome-shell/extensions/minimize-to-tray@elhan.io/prefs.js:441:45
  Preferences@/home/user/.local/share/gnome-shell/extensions/minimize-to-tray@elhan.io/prefs.js:130:25
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/minimize-to-tray@elhan.io/prefs.js:249:19
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
```
 I have removed the old settings from the previous version with dconf to be sure.

**Comment by oae** [comment]
I don't have any gnome 3.28 setup for development right now. I will try to look into it this weekend. Pull requests are welcome too :)

**Comment by JayBeeDe** [comment]
Hi,
yes sure
In the meantime, I have tested it at home on Ubuntu 20 with gnome shell version 3.36.4 and a clean dconf (/org/gnome/shell/extensions/minimize-to-tray/ removed before updating extension from v4 to v5). There is a different error but with the settings too:
```
Error: Expected type utf8 for Argument 'schema_id' but got type 'undefined'

Stack trace:
  getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:149:34
  exports.getCurrentExtensionSettings@/usr/share/gnome-shell/extensions/minimize-to-tray@elhan.io/prefs.js:441:73
  Preferences@/usr/share/gnome-shell/extensions/minimize-to-tray@elhan.io/prefs.js:130:33
  buildPrefsWidget@/usr/share/gnome-shell/extensions/minimize-to-tray@elhan.io/prefs.js:249:19
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

After manually setting the dconf key /org/gnome/shell/extensions/minimize-to-tray/apps to the following value:
`'[{"name":"Evolution","state":"enabled"},{"name":"KeePassXC","state":"enabled"},{"name":"Telegram Desktop","state":"enabled"}]'`
I get the extension working fine, but still the same message is appearing when trying to display the extension settings...

**Comment by oae** [comment]
dconf types are different now. If you put those values it shouldn't work. The extension is not updated on extension.gnome.org yet. How did you install it? Can you provide the steps so I can reproduce it?

**Comment by JayBeeDe** [comment]
> dconf types are different now. If you put those values it shouldn't work. The extension is not updated on extension.gnome.org yet. How did you install it? Can you provide the steps so I can reproduce it?

With an ansible playbook:

File gnome.yaml
```yaml
---
- hosts: all
  vars:
    user: myuser
    fullname: "JayBeeDe"
    email: ""
  become: yes
  become_user: "{{ user }}"
  environment:
    HOME: "/home/{{ user }}"
    USER: "{{ user }}"
    USERNAME: "{{ user }}"
    LOGNAME: "{{ user }}"
    
  tasks:
    - include: gnome-extensions.yaml
      with_items:
      - https://github.com/oae/gnome-shell-minimize-to-tray/releases/download/v5/minimize-to-tray@elhan.io.zip

    - name: Configuring minimize-to-tray extension...
      dconf: key="/org/gnome/shell/extensions/minimize-to-tray/apps" value="'[{\"name\":\"Evolution\",\"state\":\"enabled\"},{\"name\":\"KeePassXC\",\"state\":\"enabled\"},{\"name\":\"Telegram Desktop\",\"state\":\"enabled\"}]'"
```

File gnome-extensions.yaml
```yaml
    - name: Preparing installation...
      file:
        path: /usr/share/gnome-shell/extensions/tmp/
        state: absent
      become: yes
      become_user: "root"

    - name: Setting tmp directory...
      file:
        path: /usr/share/gnome-shell/extensions/tmp/
        state: directory
        mode: '0777'
        owner: root
        group: root
      become: yes
      become_user: "root"

    - name: Downloading Extension...
      unarchive:
        src: "{{ item }}"
        dest: /usr/share/gnome-shell/extensions/tmp/
        remote_src: yes
        mode: '0777'
        owner: root
        group: root
      become: yes
      become_user: "root"

    - name: Reading metadata...
      shell: cat /usr/share/gnome-shell/extensions/tmp/metadata.json
      register: json

    - name: Parsing metadata...
      set_fact:
        uuid: "{{ (json.stdout | from_json).uuid }}"

    - name: Checking if extension is already (sytem wide) installed...
      stat:
        path: "/usr/share/gnome-shell/extensions/{{ uuid }}"
      register: p

    - name: Logical evaluation...
      set_fact:
        toBeInstalled: yes
      when: p.stat.isdir is not defined or not p.stat.isdir

    - name: Logical evaluation...
      set_fact:
        toBeInstalled: no
      when: p.stat.isdir is defined and p.stat.isdir

    - name: "Installing extension {{ uuid }}..."
      shell: mv "/usr/share/gnome-shell/extensions/tmp/" "/usr/share/gnome-shell/extensions/{{ uuid }}"
      become: yes
      become_user: "root"
      when: toBeInstalled

    - name: Reading configuration...
      shell: dconf read /org/gnome/shell/enabled-extensions | sed -r "s:\]$::g"
      register: extlst
    
    - name: Pre-processing data...
      set_fact:
        extlst: "{{ extlst.stdout }}"

    - name: Processing data...
      set_fact:
        extlst: "{{ extlst }}, "
      when: extlst != "[" and extlst != ""

    - name: Processing data...
      set_fact:
        extlst: "[{{ extlst }}"
      when: extlst == ""

    - name: Enabling extension...
      dconf: key="/org/gnome/shell/development-tools" value="false"
      when: toBeInstalled

    - name: "Enabling extension {{ uuid }}..."
      dconf: key="/org/gnome/shell/enabled-extensions" value="{{ extlst }}'{{ uuid }}']"
      when: toBeInstalled

    - name: Updating dconf...
      shell: dconf update 2>/dev/null
      ignore_errors: yes
      when: toBeInstalled
```
